name: SD2
version: '1.0-SNAPSHOT'
main: ru.batr.sD2.SD2
api-version: '1.21'
authors: [ batr ]
permissions:
  sd.admin:
    default: false
commands:
  sd:
    alies:
      - ัะด
      - balt
    permission: sd.admin